version: '3.9'

# rede pela qual os serviços vão se comunicar 
networks:
  mvc:

# Serviços disponivéis no container
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_mvc
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9004:9004"
    networks: 
      - mvc

  postgres:
    image: postgres
    container_name: postgres_mvc
    ports: 
      - "9306:5432"
    environment: 
      POSTGRES_DB: mvc_db
      POSTGRES_USER: mvc_db
      POSTGRES_PASSWORD: 123456789
    networks: 
      - mvc
    volumes: 
      - ./postgres:/var/lib/postgresql/data

  nginx: 
    image: nginx:stable-alpine'
    container_name: nginx_mvc
    ports: 
      - "7000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - mvc

  composer:
    image: composer:latest
    container_name: composer_mvc
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks: 
      - mvc
  
  npm: 
    image: node:13.7
    container_name: npm_mvc
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']